[tools]
selene = { github = "Kampfkarren/selene", version = "=0.19.1" }
stylua = { github = "JohnnyMorganz/StyLua", version = "=0.13.1" }
luau-lsp = { github = "johnnymorganz/luau-lsp", version = "=1.23.0"}
darklua = { github = "seaofvoices/darklua", version = "=0.12.1" }
wally = { github = "UpliftGames/wally", version = "=0.3.2" }
rojo = { github = "rojo-rbx/rojo", version = "=7.4.1" }
